version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gfn-node-app
    network_mode: host
    env_file:
      - .env
    volumes:
      - .:/app
    command: >
      sh -c "npx prisma generate && npx tsx src/api-gateway/index.ts"
